'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "Funcionalidad para autoguardar de My.Settings"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property REQUISICION_SERVICIO() As String
            Get
                Return CType(Me("REQUISICION_SERVICIO"),String)
            End Get
            Set
                Me("REQUISICION_SERVICIO") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property REQUISICION_SOLICITA() As String
            Get
                Return CType(Me("REQUISICION_SOLICITA"),String)
            End Get
            Set
                Me("REQUISICION_SOLICITA") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property REQUISICION_REVISA() As String
            Get
                Return CType(Me("REQUISICION_REVISA"),String)
            End Get
            Set
                Me("REQUISICION_REVISA") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Medico Jefe")>  _
        Public Property REQUISICION_AUTORIZA() As String
            Get
                Return CType(Me("REQUISICION_AUTORIZA"),String)
            End Get
            Set
                Me("REQUISICION_AUTORIZA") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property REQUISICION_DESPACHA() As String
            Get
                Return CType(Me("REQUISICION_DESPACHA"),String)
            End Get
            Set
                Me("REQUISICION_DESPACHA") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property REQUISICION_RECIBE() As String
            Get
                Return CType(Me("REQUISICION_RECIBE"),String)
            End Get
            Set
                Me("REQUISICION_RECIBE") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Jefe Del Servicio")>  _
        Public Property REQUISICION_SOLICITA_CARGO() As String
            Get
                Return CType(Me("REQUISICION_SOLICITA_CARGO"),String)
            End Get
            Set
                Me("REQUISICION_SOLICITA_CARGO") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Guarda Almacen")>  _
        Public Property REQUISICION_REVISA_CARGO() As String
            Get
                Return CType(Me("REQUISICION_REVISA_CARGO"),String)
            End Get
            Set
                Me("REQUISICION_REVISA_CARGO") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Gerente")>  _
        Public Property REQUISICION_AUTORIZA_CARGO() As String
            Get
                Return CType(Me("REQUISICION_AUTORIZA_CARGO"),String)
            End Get
            Set
                Me("REQUISICION_AUTORIZA_CARGO") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Guarda Almacen")>  _
        Public Property REQUISICION_DESPACHA_CARGO() As String
            Get
                Return CType(Me("REQUISICION_DESPACHA_CARGO"),String)
            End Get
            Set
                Me("REQUISICION_DESPACHA_CARGO") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Jefe Del Servicio")>  _
        Public Property REQUISICION_RECIBE_CARGO() As String
            Get
                Return CType(Me("REQUISICION_RECIBE_CARGO"),String)
            End Get
            Set
                Me("REQUISICION_RECIBE_CARGO") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Material medico quirurgico para uso diario del servicio")>  _
        Public Property REQUISICION_JUSTIFICACION() As String
            Get
                Return CType(Me("REQUISICION_JUSTIFICACION"),String)
            End Get
            Set
                Me("REQUISICION_JUSTIFICACION") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property PEDIDO_SERVICIO() As String
            Get
                Return CType(Me("PEDIDO_SERVICIO"),String)
            End Get
            Set
                Me("PEDIDO_SERVICIO") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property PEDIDO_JUSTIFICACION() As String
            Get
                Return CType(Me("PEDIDO_JUSTIFICACION"),String)
            End Get
            Set
                Me("PEDIDO_JUSTIFICACION") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property PEDIDO_SOLICITA() As String
            Get
                Return CType(Me("PEDIDO_SOLICITA"),String)
            End Get
            Set
                Me("PEDIDO_SOLICITA") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Eduardo García")>  _
        Public Property PEDIDO_AUTORIZA() As String
            Get
                Return CType(Me("PEDIDO_AUTORIZA"),String)
            End Get
            Set
                Me("PEDIDO_AUTORIZA") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Dr.  Jazmy Alejandra García Figueroa")>  _
        Public Property PEDIDO_APROBACION() As String
            Get
                Return CType(Me("PEDIDO_APROBACION"),String)
            End Get
            Set
                Me("PEDIDO_APROBACION") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Jefe Del Servicio")>  _
        Public Property PEDIDO_SOLICITA_CARGO() As String
            Get
                Return CType(Me("PEDIDO_SOLICITA_CARGO"),String)
            End Get
            Set
                Me("PEDIDO_SOLICITA_CARGO") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Gerente Administrativo Financiero ")>  _
        Public Property PEDIDO_AUTORIZA_CARGO() As String
            Get
                Return CType(Me("PEDIDO_AUTORIZA_CARGO"),String)
            End Get
            Set
                Me("PEDIDO_AUTORIZA_CARGO") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Directora Ejecutiva")>  _
        Public Property PEDIDO_APROBACION_CARGO() As String
            Get
                Return CType(Me("PEDIDO_APROBACION_CARGO"),String)
            End Get
            Set
                Me("PEDIDO_APROBACION_CARGO") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Lic. Cristian Odilio Urizar Montufar")>  _
        Public Property PEDIDO_PRESUPUESTO() As String
            Get
                Return CType(Me("PEDIDO_PRESUPUESTO"),String)
            End Get
            Set
                Me("PEDIDO_PRESUPUESTO") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Jose Fernando Laynez Castro")>  _
        Public Property PEDIDO_COMPRAS() As String
            Get
                Return CType(Me("PEDIDO_COMPRAS"),String)
            End Get
            Set
                Me("PEDIDO_COMPRAS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("13")>  _
        Public Property PEDIDO_PROG() As String
            Get
                Return CType(Me("PEDIDO_PROG"),String)
            End Get
            Set
                Me("PEDIDO_PROG") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("00")>  _
        Public Property PEDIDO_SUBP() As String
            Get
                Return CType(Me("PEDIDO_SUBP"),String)
            End Get
            Set
                Me("PEDIDO_SUBP") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("00")>  _
        Public Property PEDIDO_PROY() As String
            Get
                Return CType(Me("PEDIDO_PROY"),String)
            End Get
            Set
                Me("PEDIDO_PROY") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("02")>  _
        Public Property PEDIDO_ACT() As String
            Get
                Return CType(Me("PEDIDO_ACT"),String)
            End Get
            Set
                Me("PEDIDO_ACT") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("00")>  _
        Public Property PEDIDO_OBRA() As String
            Get
                Return CType(Me("PEDIDO_OBRA"),String)
            End Get
            Set
                Me("PEDIDO_OBRA") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1401")>  _
        Public Property PEDIDO_UB_GEO() As String
            Get
                Return CType(Me("PEDIDO_UB_GEO"),String)
            End Get
            Set
                Me("PEDIDO_UB_GEO") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("11")>  _
        Public Property PEDIDO_FTE_FIN() As String
            Get
                Return CType(Me("PEDIDO_FTE_FIN"),String)
            End Get
            Set
                Me("PEDIDO_FTE_FIN") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("77903333")>  _
        Public Property PEDIDO_TELEFONO() As String
            Get
                Return CType(Me("PEDIDO_TELEFONO"),String)
            End Get
            Set
                Me("PEDIDO_TELEFONO") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.SolicitudDePedidoYRequisicion.My.MySettings
            Get
                Return Global.SolicitudDePedidoYRequisicion.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
